
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Sign_Comillas = 2;
  public static final int Inicio_Fila = 23;
  public static final int Inicio_Tabla = 21;
  public static final int Inicio_Imagen = 32;
  public static final int Num_Float = 38;
  public static final int Num_Int = 37;
  public static final int Inicio_Html = 13;
  public static final int Et_Alto = 35;
  public static final int Fin_Cuerpo = 19;
  public static final int Nue_Columna = 25;
  public static final int Tab_Borde = 20;
  public static final int Op_Producto = 11;
  public static final int Error = 42;
  public static final int Sign_Igual = 3;
  public static final int Op_Resta = 9;
  public static final int Ins_Imprimir = 27;
  public static final int Datos = 39;
  public static final int Salto_Linea = 28;
  public static final int Abrir_LLave = 4;
  public static final int Fin_Lista = 30;
  public static final int EOF = 0;
  public static final int Et_Ancho = 34;
  public static final int error = 1;
  public static final int Fin_Tabla = 22;
  public static final int Fin_Encabezado = 16;
  public static final int Webpage = 41;
  public static final int Inicio_Cuerpo = 18;
  public static final int Op_Division = 12;
  public static final int Correo = 40;
  public static final int Sign_Coma = 6;
  public static final int Punto_Coma = 7;
  public static final int Fin_Imagen = 36;
  public static final int Inicio_Encabezado = 15;
  public static final int Dos_puntos = 10;
  public static final int Nombre_Imagen = 33;
  public static final int Fuent_Negrita = 26;
  public static final int Fin_Fila = 24;
  public static final int Fin_Html = 14;
  public static final int Op_Suma = 8;
  public static final int Et_Enlace = 31;
  public static final int Cerrar_LLave = 5;
  public static final int Inicio_Lista = 29;
  public static final int Et_Titulo = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Sign_Comillas",
  "Sign_Igual",
  "Abrir_LLave",
  "Cerrar_LLave",
  "Sign_Coma",
  "Punto_Coma",
  "Op_Suma",
  "Op_Resta",
  "Dos_puntos",
  "Op_Producto",
  "Op_Division",
  "Inicio_Html",
  "Fin_Html",
  "Inicio_Encabezado",
  "Fin_Encabezado",
  "Et_Titulo",
  "Inicio_Cuerpo",
  "Fin_Cuerpo",
  "Tab_Borde",
  "Inicio_Tabla",
  "Fin_Tabla",
  "Inicio_Fila",
  "Fin_Fila",
  "Nue_Columna",
  "Fuent_Negrita",
  "Ins_Imprimir",
  "Salto_Linea",
  "Inicio_Lista",
  "Fin_Lista",
  "Et_Enlace",
  "Inicio_Imagen",
  "Nombre_Imagen",
  "Et_Ancho",
  "Et_Alto",
  "Fin_Imagen",
  "Num_Int",
  "Num_Float",
  "Datos",
  "Correo",
  "Webpage",
  "Error"
  };
}

