/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Analizador;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.io.Reader;
import java.io.StringReader;
import java.io.StringWriter;
import java.nio.file.Files;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java_cup.runtime.Scanner;
import java_cup.runtime.Symbol;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DavMijan
 */
public class Visual extends javax.swing.JFrame {
    DefaultTableModel modelo;
    /**
     * Creates new form Visual
     */
    public Visual() {
        initComponents();
            Btn2.setEnabled(false);
            BtnSintactico.setEnabled(false);
            BtnGenerador.setEnabled(false);
        modelo=new DefaultTableModel();
        modelo.addColumn("  Dato_Origen  ");
        modelo.addColumn("  Tipo_Dato  ");
          DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
          tcr.setHorizontalAlignment(SwingConstants.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnBuscar = new javax.swing.JButton();
        Text2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Texto = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        LengDestino = new javax.swing.JTextArea();
        BtnSintactico = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        Resultado = new javax.swing.JTextArea();
        BtnGenerador = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Btn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        Texto.setColumns(20);
        Texto.setRows(5);
        jScrollPane2.setViewportView(Texto);

        jLabel2.setText("Texto Origen");

        jLabel3.setText("Errores y Resultados");

        LengDestino.setColumns(20);
        LengDestino.setRows(5);
        jScrollPane3.setViewportView(LengDestino);

        BtnSintactico.setText("Analizar Lexico");
        BtnSintactico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSintacticoActionPerformed(evt);
            }
        });

        Resultado.setColumns(20);
        Resultado.setRows(5);
        jScrollPane4.setViewportView(Resultado);

        BtnGenerador.setText("Generar HTML");
        BtnGenerador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGeneradorActionPerformed(evt);
            }
        });

        jLabel4.setText("Lenguaje Destino");

        Btn2.setText("Analizar Sintaxis");
        Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Text2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnSintactico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnGenerador))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel2)
                                        .addGap(242, 242, 242)
                                        .addComponent(jLabel4)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBuscar)
                    .addComponent(Text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSintactico)
                    .addComponent(BtnGenerador)
                    .addComponent(Btn2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        borrar();        
        JFileChooser fc=new JFileChooser();
        int selection = fc.showOpenDialog(this);
        String []info = new String[2];
        if(selection == JFileChooser.APPROVE_OPTION){
        File fichero = fc.getSelectedFile();        
        this.Text2.setText(fichero.getAbsolutePath());
        try {
            String ST = new String(Files.readAllBytes(fichero.toPath()));
            Texto.setText(ST); 
            BtnSintactico.setEnabled(true);
        } catch (FileNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(Level.SEVERE, null, ex);
        }
  
        }   
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void BtnSintacticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSintacticoActionPerformed
    
        try {
            Btn2.setEnabled(true);
            Resultado.setText("");
            String ST = Texto.getText();
            LexerCup scann = new LexerCup( new BufferedReader( new StringReader(ST)));
            Resultado.setText(""+LexerCup.ErroresLexicos);
            parser parser = new parser( scann);
            parser.parse();
            
        } catch (Exception ex) {
            
            //ex.printStackTrace();
        }


    }//GEN-LAST:event_BtnSintacticoActionPerformed

    private void BtnGeneradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGeneradorActionPerformed
        try {
            String a = System.getProperty("user.name");
            Date myDate = new Date();
            String ruta = "C:\\Users\\"+a+"\\Desktop\\Html-Generado-"+new SimpleDateFormat("dd-MM-yyyy").format(myDate)+".html";
            File file = new File(ruta);

            if (!file.exists()) {
                file.createNewFile();
            };
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(LengDestino.getText());
            bw.close();
            Resultado.setText("Documento Html Generado con exito: " + ruta);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BtnGeneradorActionPerformed

    private void Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2ActionPerformed
        String ST = Texto.getText();
        parser s = new parser(new Analizador.LexerCup(new StringReader(ST))); 
        Resultado.setText(ST);
        String resultado = "";
        try { 
            s.parse();
            LengDestino.setText(s.resultado);
            //ErroresText.setText(s.resultado);
            Resultado.setText("Analisis realizado correctamente");
            Resultado.setForeground(new Color(25, 111, 61));
            BtnGenerador.setEnabled(true);
        } catch (Exception ex) {
            Symbol sym = s.getS();
            LengDestino.setText(s.resultado);
            Resultado.setText("Error de sintaxis. Linea "+(sym.right+1)+" Columna: "+(sym.left+1)+", Texto: \""+sym.value+ "\"");
            Resultado.setForeground(Color.red);
        }
    }//GEN-LAST:event_Btn2ActionPerformed
    public void borrar(){
        try {
            BtnSintactico.setEnabled(false);
            BtnGenerador.setEnabled(false);
            Texto.setText("");
            LengDestino.setText("");
            Resultado.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un Error"+e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn2;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnGenerador;
    private javax.swing.JButton BtnSintactico;
    private javax.swing.JTextArea LengDestino;
    private javax.swing.JTextArea Resultado;
    private javax.swing.JTextField Text2;
    private javax.swing.JTextArea Texto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
